# Adapted from example in docker documentation
# Link all containers together in here
version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code
    expose:
       - 8000
    links:
      - "redis"
    command: python /code/mysite/manage.py runserver 0.0.0.0:8000

  redis:
    image: redis
    expose:
      - 6379
  
  nginx:
    restart: always
    build: ./nginx/
    # "web" container starts up first, then "nginx" start up
    depends_on:
      - web
    ports:
      - "80:80"
    links:
      - web:web
